name: Secret to file

on:
  workflow_dispatch:
  
env:
   MY_SECRET: ${{ secrets.MY_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: print secrets
      run: |
          touch config.ini
          echo "MY_SECRET" >> config.ini
          sed -i "s/\${MY_SECRET}/${{secrets.MY_SECRET}}/" config.ini
          cat config.ini
      shell: bash
      env:
        MY_SECRET: ${{secrets.KEY}}
