name: Create Release Notes

on:
  workflow_dispatch:
    inputs:
      fromTag:
        description: 'The from-tag version (e.g. "0.4.7)'
        required: true
        default: 'x.x.x'
      toTag:
        description: 'The to-tag version (e.g. "0.4.33)'
        required: true
        default: 'x.x.x'

jobs:
  create-release:
    name: 'Create Release Notes'
    runs-on: ubuntu-latest
    env:
      fromTag: v${{ github.event.inputs.fromTag }}
      toTag: v${{ github.event.inputs.toTag }}
    steps:
      # Link to Action: https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Loads full history which is required for tagging
          fetch-depth: 0

      # Link to Action: https://github.com/marketplace/actions/tag-exists-action
      - name: 'Check if from-tag exists'
        uses: mukunku/tag-exists-action@v1.2.0
        id: checkFromTag
        with:
          tag: ${{ env.fromTag }}
        env:
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
      - if: ${{ steps.checkFromTag.outputs.exists == 'false' }}
        run: |
          echo "::error ::Version Tag ${{ env.fromTag }} does not exist"
          exit 1

      # Link to Action: https://github.com/marketplace/actions/tag-exists-action
      - name: 'Check if to-tag exists'
        uses: mukunku/tag-exists-action@v1.2.0
        id: checkToTag
        with:
          tag: ${{ env.toTag }}
        env:
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
      - if: ${{ steps.checkToTag.outputs.exists == 'false' }}
        run: |
          echo "::error ::Version Tag ${{ env.toTag }} does not exist"
          exit 1

      # Link to Action: https://github.com/marketplace/actions/release-changelog-builder
      - name: Build Changelog
        id: buildChangelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fromTag: "${{ env.fromTag }}"
          toTag: "${{ env.toTag }}"
          commitMode: "true"
          ignorePreReleases: "false"
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                  "title": "JIRA Commits",
                  "rules": {
                    "pattern": "BADZ-"
                  }
                }
              ],
              "pr_template": "#{{TITLE}}\n",
            }

      # Link to Action: https://github.com/marketplace/actions/gh-release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Release ${{ env.toTag }}
            **Full Changelog**: ${{ github.server_url }}/${{ github.repository }}/compare/${{ env.fromTag }}...${{ env.toTag }}
            **Changelog**: 
            ${{ steps.buildChangelog.outputs.changelog }}
          name: Production release ${{ env.toTag }}
          tag_name: ${{ env.toTag }}
