name: Create Release Notes

on:
  workflow_dispatch:
    inputs:
      fromTag:
        description: 'The from-tag version (e.g. "0.4.7)'
        required: true
        default: 'x.x.x'
      toTag:
        description: 'The to-tag version (e.g. "0.4.33)'
        required: true
        default: 'x.x.x'

jobs:
  create-release:
    name: 'Create Release Notes'
    runs-on: ubuntu-latest
    env:
      fromTag: v${{ github.event.inputs.fromTag }}
      toTag: v${{ github.event.inputs.toTag }}
    steps:
      # Link to Action: https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Loads full history which is required for tagging
          fetch-depth: 0

      # Link to Action: https://github.com/marketplace/actions/tag-exists-action
      - name: 'Check if from-tag exists'
        uses: mukunku/tag-exists-action@v1.2.0
        id: checkFromTag
        with:
          tag: ${{ env.fromTag }}
        env:
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
      - if: ${{ steps.checkFromTag.outputs.exists == 'false' }}
        run: |
          echo "::error ::Version Tag ${{ env.fromTag }} does not exist"
          exit 1

      # Link to Action: https://github.com/marketplace/actions/tag-exists-action
      - name: 'Check if to-tag exists'
        uses: mukunku/tag-exists-action@v1.2.0
        id: checkToTag
        with:
          tag: ${{ env.toTag }}
        env:
          GITHUB_TOKEN: ${{ env.GH_TOKEN }}
      - if: ${{ steps.checkToTag.outputs.exists == 'false' }}
        run: |
          echo "::error ::Version Tag ${{ env.toTag }} does not exist"
          exit 1

      # Link to Action: https://github.com/marketplace/actions/release-changelog-builder
      - name: Build Changelog
        id: buildChangelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fromTag: "${{ env.fromTag }}"
          toTag: "${{ env.toTag }}"
          commitMode: "true"
          ignorePreReleases: "false"

      # Link to Action: https://github.com/marketplace/actions/gh-release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            changelog: ${{ steps.buildChangelog.outputs.changelog }}
            outputs: ${{ steps.buildChangelog.outputs }}
            buildChangelog: ${{ steps.buildChangelog }}
            Release ${{ env.toTag }}
            **Full Changelog**: ${{ github.server_url }}/${{ github.repository }}/compare/${{ env.fromTag }}...${{ env.toTag }}
            **Changelog**: 
            ```
            ${{ steps.buildChangelog.outputs.changelog }}
            ```
            **changelog**: ${{ steps.buildChangelog.outputs.changelog }}
            **pull_requests**: ${{ steps.buildChangelog.outputs.pull_requests }}
            **owner**: ${{ steps.buildChangelog.outputs.owner }}
            **repo**: ${{ steps.buildChangelog.outputs.repo }}
            **fromTag**: ${{ steps.buildChangelog.outputs.fromTag }}
            **toTag**: ${{ steps.buildChangelog.outputs.toTag }}
            **failed**: ${{ steps.buildChangelog.outputs.failed }}
            **categorized_prs**: ${{ steps.buildChangelog.outputs.categorized_prs }}
            **uncategorized_prs**: ${{ steps.buildChangelog.outputs.uncategorized_prs }}
            **open_prs**: ${{ steps.buildChangelog.outputs.open_prs }}

          name: Production release ${{ env.toTag }}
          tag_name: ${{ env.toTag }}
