name: Test

env:
  ENV_VAR : 1

on:
  workflow_dispatch:
    inputs:
      stage:
        type: choice
        description: 'Stage'
        options:
          - dev
          - preprod
          - prod
        default: preprod
      version:
        description: 'Version (e.g. "1.0.1")'
        required: true
        default: 'x.x.x'

jobs:
  deploy:
    if: contains(['dev', 'preprod', 'prod'], ${{ github.event.inputs.stage}})
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.stage}}
    name: 'Deploy to ${{ github.event.inputs.stage}}'
    steps:
      - name: 'Setup stage variables'
        run: |
          if [ '${{ github.event.inputs.stage }}' = 'dev' ]; then
            echo "OPENSHIFT_NAMESPACE=bra-dev-axa-ch" >> $GITHUB_ENV
            echo "VALUE_OPTION=./helm/bra-backend/values.dev.yaml" >> $GITHUB_ENV
            echo "MONGODB_SECRET_NAME=MONGODB_PASSWORD_DEV" >> $GITHUB_ENV
          elif [ '${{ github.event.inputs.stage }}' = 'preprod' ]; then
            echo "OPENSHIFT_NAMESPACE=bra-preprod-axa-ch" >> $GITHUB_ENV
            echo "VALUE_OPTION=./helm/bra-backend/values.preprod.yaml" >> $GITHUB_ENV
            echo "MONGODB_SECRET_NAME=MONGODB_PASSWORD_PREPROD" >> $GITHUB_ENV
          elif [ '${{ github.event.inputs.stage }}' = 'prod' ]; then 
            echo "OPENSHIFT_NAMESPACE=bra-prod-axa-ch" >> $GITHUB_ENV
            echo "VALUE_OPTION=./helm/bra-backend/values.prod.yaml" >> $GITHUB_ENV
            echo "MONGODB_SECRET_NAME=MONGODB_PASSWORD_PROD" >> $GITHUB_ENV
          fi

      - name: 'output'
        run: "echo ${{ secrets[env.MONGODB_SECRET_NAME]] }}"
